### ISSUE TITLE
?___store= in the languages switcher

### ISSUE THREAD

**Issue by kai1083** [Knectar/Magento-Store-Codes#6]
the default store have ?___store= in the  languages switcher.
in the languages.phtml i have setup <?php echo $_lang->getCurrentUrl(false) ?> but it not works

**Comment by clockworkgeek** [comment]
I see.  In the function `Mage_Core_Model_Store::getCurrentUrl` it has the line:

    if (!Mage::getStoreConfigFlag(Mage_Core_Model_Store::XML_PATH_STORE_IN_URL, $this->getCode())) {
        $storeParsedQuery['___store'] = $this->getCode();
    }

which means if store codes are disabled for a store then add the `___store` query parameter.  Since this extension disables store codes for the default store, that is exactly what is happening.

I don't want to override `Mage_Core_Model_Store` because it's such an important class and I don't yet have another way of stopping store codes.  This might take me some time to fix.

**Comment by kai1083** [comment]
okay thanks, i´m waiting of a fix :)

**Comment by kai1083** [comment]
any news for a fix? or dirty trick for the languages switcher

**Comment by clockworkgeek** [comment]
I cannot fix this but there is a workaround.  Copy the template `page/switch/languages.phtml` to your own theme (to avoid breaking other themes) and change `echo $_lang->getCurrentUrl()` to `echo $this->getUrl('', array('_current'=>true, '_store'=>$_lang, '_use_rewrite'=>true))`

The listed parameters look unusual and behave like magic but are described [here](https://magento2.atlassian.net/wiki/display/m1wiki/getUrl%28%29+Function+Parameters).
