### ISSUE TITLE
Admin Url problem

### ISSUE THREAD

**Issue by ebabis** [Knectar/Magento-Store-Codes#8]
Hi,
I have problem with admin url, it shows www.my-site.com/admin/admin/ that problem disappears when i set store codes to no but i need to show them except the default store view. 

Can you add please this as fix when we choose the default store view to no to remove also the second admin from the url ?

regards

**Comment by wbrawner** [comment]
~~This problem also affects me~~

EDIT: This is caused by Magento itself. I tested on a vanilla installation and turning on the store codes causes this to happen, even if the module isn't installed and hasn't ever been installed.

**Comment by clockworkgeek** [comment]
I'm afraid changing this will cause problems.

The second "admin" identifies the "Mage_Adminhtml" module, third party modules can and sometimes do have different identifiers in place there, so that cannot be removed.

The first "admin" is a store code because the backend is a store in itself.  Each store must be differentiable from the others and when there is only one domain we use store codes to do that.  It is possible to hide that code for one store only, removing this "admin" would break that.
